const MINIBUFFET_FETCH_SUCCESS = 'minibuffet/FETCH_SUCCESS'
const MINIBUFFET_UPDATE_SEARCHINFO = 'minibuffet/UPDATE_SEARCHINFO'
const MINIBUFFET_UPDATE_ITEMS = "minibuffet/UPDATE_ITEMS"
const MINIBUFFET_REMOVE_ITEMS = "minibuffet/REMOVE_ITEMS"
const MINIBUFFET_CLEAR_CART = "minibuffet/CLEAR_CART"
const MINIBUFFET_CHOOSE_PRODUCT_LIST = "minibuffet/CHOOSE_PRODUCT_LIST"

const MINIBUFFET_CONFIRM_ORDER_SUCCESS = "minibuffet/CONFIRM_ORDER_SUCCESS"
const MINIBUFFET_CONFIRM_ORDER_FAILURE = "minibuffet/CONFIRM_ORDER_FAILURE"
const MINIBUFFET_CANCEL_ITEM_SUCCESS = "minibuffet/CANCEL_ITEM_SUCCESS"
const MINIBUFFET_CANCEL_ITEM_FAILURE = "minibuffet/CANCEL_ITEM_FAILURE"

export {
    MINIBUFFET_FETCH_SUCCESS,
    MINIBUFFET_CHOOSE_PRODUCT_LIST,
    MINIBUFFET_UPDATE_SEARCHINFO,

    // carts
    MINIBUFFET_UPDATE_ITEMS,
    MINIBUFFET_REMOVE_ITEMS,
    MINIBUFFET_CLEAR_CART,

    MINIBUFFET_CONFIRM_ORDER_SUCCESS,
    MINIBUFFET_CONFIRM_ORDER_FAILURE,
    MINIBUFFET_CANCEL_ITEM_SUCCESS,
    MINIBUFFET_CANCEL_ITEM_FAILURE
}