const MEALBOX_FETCH_SUCCESS = 'mealbox/FETCH_SUCCESS'
const MEALBOX_FILTER = 'mealbox/FILTER'
const MEALBOX_RESET = 'mealbox/RESET'
const MEALBOX_OPEN_FILTER = 'mealbox/OPEN_FILTER'
const MEALBOX_CLOSE_FILTER = 'mealbox/CLOSE_FILTER'
const MEALBOX_SWITCH_ADDITIONAL_FILTER_OPTION = 'mealbox/SWITCH_FILTER_OPTION'
const MEALBOX_CLEAR_ADDITIONAL_FILTER = 'mealbox/CLEAR_ADDITIONAL_FILTER'
const MEALBOX_APPLY_ADDITIONAL_FILTER = 'mealbox/APPLY_ADDITIONAL_FILTER'
const MEALBOX_CHANGE_MEALTIME_TYPE = 'mealbox/MEALBOX_CHANGE_MEALTIME_TYPE'

const MEALBOX_REMOVE_ITEM = "mealbox/REMOVE_ITEM"
const MEALBOX_UPDATE_ITEMS = "mealbox/UPDATE_ITEMS"

const MEALBOX_CONFIRM_ORDER_SUCCESS = "mealbox/CONFIRM_ORDER_SUCCESS"
const MEALBOX_CONFIRM_ORDER_FAILURE = "mealbox/CONFIRM_ORDER_FAILURE"

const MEALBOX_CANCEL_ITEM_SUCCESS = "mealbox/CANCEL_ITEM_SUCCESS"
const MEALBOX_CANCEL_ITEM_FAILURE = "mealbox/CANCEL_ITEM_FAILURE"

const MEALBOX_CLEAR_CART = "mealbox/CLEAR_CART"

export {
    MEALBOX_FETCH_SUCCESS,
    MEALBOX_FILTER,
    MEALBOX_RESET,
    MEALBOX_OPEN_FILTER,
    MEALBOX_CLOSE_FILTER,
    MEALBOX_SWITCH_ADDITIONAL_FILTER_OPTION,
    MEALBOX_CLEAR_ADDITIONAL_FILTER,
    MEALBOX_APPLY_ADDITIONAL_FILTER,
    MEALBOX_CHANGE_MEALTIME_TYPE,

    // carts
    MEALBOX_REMOVE_ITEM,
    MEALBOX_UPDATE_ITEMS,
    MEALBOX_CONFIRM_ORDER_SUCCESS,
    MEALBOX_CONFIRM_ORDER_FAILURE,
    MEALBOX_CANCEL_ITEM_SUCCESS,
    MEALBOX_CANCEL_ITEM_FAILURE,
    MEALBOX_CLEAR_CART
}