const USER_FETCHING = "user/FETCHING"
const USER_CREATE_TOKEN_SUCCESS = "user/CREATE_TOKEN_SUCCESS"
const USER_CREATE_TOKEN_FAILURE = "user/CREATE_TOKEN_FAILURE"
const USER_RECOVER_ACCOUNT_FINISH = "user/RECOVER_ACCOUNT_FINISH"
const USER_GET_INFO_SUCCESS = "user/GET_INFO_SUCCESS"
const USER_GET_INFO_FAILURE = "user/GET_INFO_FAILURE"
const USER_UPDATE_INFO_SUCCESS = "user/UPDATE_INFO_SUCCESS"
const USER_CHANGE_ADDRESS = "user/CHANGE_ADDRESS"
const USER_ADD_ADDRESS_SUCCESS = "user/ADD_ADDRESS_SUCCESS"
const USER_UPDATE_ADDRESS_SUCCESS = "user/UPDATE_ADDRESS_SUCCESS"
const USER_DELETE_ADDRESS_SUCCESS = "user/DELETE_ADDRESS_SUCCESS"
const USER_UPDATE_HISTORY = "user/UPDATE_HISTORY"
const USER_GET_TODAY_SHIPPING_ADDRESSES = "user/GET_TODAY_SHIPPING_ADDRESSES"
const USER_GET_NOTIFICATION = "user/GET_NOTIFICATION"
const USER_ADD_TEMP_CREDIT_RECORD = "user/ADD_TEMP_CREDIT_RECORD"
const USER_UPDATE_CREDIT = "user/UPDATE_CREDIT"
const USER_UPDATE_CUSTOM_DELIVERY_TIME = "user/UPDATE_CUSTOM_DELIVERY_TIME"
const USER_POST_REVIEW_FAILURE = "user/POST_REVIEW_FAILURE"
const USER_SEE_STORE_REVIEW_POPUP = "user/SEE_STORE_REVIEW_POPUP"
const USER_LOG_OUT = "user/LOG_OUT"

export {
    USER_FETCHING,
    USER_CREATE_TOKEN_SUCCESS,
    USER_CREATE_TOKEN_FAILURE,
    USER_RECOVER_ACCOUNT_FINISH,
    USER_GET_INFO_SUCCESS,
    USER_GET_INFO_FAILURE,
    USER_UPDATE_INFO_SUCCESS,
    USER_CHANGE_ADDRESS,
    USER_ADD_ADDRESS_SUCCESS,
    USER_UPDATE_ADDRESS_SUCCESS,
    USER_DELETE_ADDRESS_SUCCESS,
    USER_UPDATE_HISTORY,
    USER_GET_TODAY_SHIPPING_ADDRESSES,
    USER_GET_NOTIFICATION,
    USER_ADD_TEMP_CREDIT_RECORD,
    USER_UPDATE_CREDIT,
    USER_UPDATE_CUSTOM_DELIVERY_TIME,
    USER_POST_REVIEW_FAILURE,
    USER_SEE_STORE_REVIEW_POPUP,
    USER_LOG_OUT,
}